const nintendoSidebarTitles = [
  { id: "0", title: "Color TV-Game" },
  { id: "1", title: "Game & Watch" },
  { id: "2", title: "Nintendo Entertainment System (NES)" },
  { id: "3", title: "Game Boy" },
  { id: "4", title: "Super Nintendo Entertainment System (SNES)" },
  { id: "5", title: "Virtual Boy" },
  { id: "6", title: "Game Boy Pocket" },
  { id: "7", title: "Nintendo 64" },
  { id: "8", title: "Game Boy Light" },
  { id: "9", title: "Game Boy Color" },
  { id: "10", title: "Game Boy Advance" },
  { id: "11", title: "Pokémon mini" },
  { id: "12", title: "Nintendo GameCube" },
  { id: "13", title: "Panasonic Q" },
  { id: "14", title: "Game Boy Advance SP" },
  { id: "15", title: "Nintendo DS" },
  { id: "16", title: "Game Boy Micro" },
  { id: "17", title: "Nintendo DS Lite" },
  { id: "18", title: "Nintendo Wii" },
  { id: "19", title: "Nintendo DSi" },
  { id: "20", title: "Nintendo DSi XL" },
  { id: "21", title: "Nintendo 3DS" },
  { id: "22", title: "Nintendo 3DS XL" },
  { id: "23", title: "Nintendo Wii U" },
  { id: "24", title: "Nintendo Wii Mini" },
  { id: "25", title: "Nintendo 2DS" },
  { id: "26", title: "New Nintendo 3DS" },
  { id: "27", title: "New Nintendo 3DS XL" },
  { id: "28", title: "Nintendo Switch" },
  { id: "29", title: "New Nintendo 2DS XL" },
  { id: "30", title: "Nintendo Switch Lite" },
  { id: "31", title: "Nintendo Switch OLED" },
  { id: "32", title: "Nintendo Switch 2" },
];

export default nintendoSidebarTitles;
